version: "3"

services:
  client:
    build:
        context: ./client
        dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000

  signal:
    build:
        context: ./signal
        dockerfile: Dockerfile
    restart: always
    ports:
      - 3001:3001
